/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-11-29 at 12:45:57 UTC 
 * Modify at your own risk.
 */

package com.trip.expensemanager.tosyncendpoint;

/**
 * Service definition for Tosyncendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TosyncendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Tosyncendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the tosyncendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://healthy-dolphin-679.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "tosyncendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Tosyncendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Tosyncendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getToSync".
   *
   * This request holds the parameters needed by the tosyncendpoint server.  After setting any
   * optional parameters, call the {@link GetToSync#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetToSync getToSync(java.lang.Long id) throws java.io.IOException {
    GetToSync result = new GetToSync(id);
    initialize(result);
    return result;
  }

  public class GetToSync extends TosyncendpointRequest<com.trip.expensemanager.tosyncendpoint.model.ToSync> {

    private static final String REST_PATH = "tosync/{id}";

    /**
     * Create a request for the method "getToSync".
     *
     * This request holds the parameters needed by the the tosyncendpoint server.  After setting any
     * optional parameters, call the {@link GetToSync#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetToSync#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetToSync(java.lang.Long id) {
      super(Tosyncendpoint.this, "GET", REST_PATH, null, com.trip.expensemanager.tosyncendpoint.model.ToSync.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetToSync setAlt(java.lang.String alt) {
      return (GetToSync) super.setAlt(alt);
    }

    @Override
    public GetToSync setFields(java.lang.String fields) {
      return (GetToSync) super.setFields(fields);
    }

    @Override
    public GetToSync setKey(java.lang.String key) {
      return (GetToSync) super.setKey(key);
    }

    @Override
    public GetToSync setOauthToken(java.lang.String oauthToken) {
      return (GetToSync) super.setOauthToken(oauthToken);
    }

    @Override
    public GetToSync setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetToSync) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetToSync setQuotaUser(java.lang.String quotaUser) {
      return (GetToSync) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetToSync setUserIp(java.lang.String userIp) {
      return (GetToSync) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetToSync setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetToSync set(String parameterName, Object value) {
      return (GetToSync) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertToSync".
   *
   * This request holds the parameters needed by the tosyncendpoint server.  After setting any
   * optional parameters, call the {@link InsertToSync#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.trip.expensemanager.tosyncendpoint.model.ToSync}
   * @return the request
   */
  public InsertToSync insertToSync(com.trip.expensemanager.tosyncendpoint.model.ToSync content) throws java.io.IOException {
    InsertToSync result = new InsertToSync(content);
    initialize(result);
    return result;
  }

  public class InsertToSync extends TosyncendpointRequest<com.trip.expensemanager.tosyncendpoint.model.ToSync> {

    private static final String REST_PATH = "tosync";

    /**
     * Create a request for the method "insertToSync".
     *
     * This request holds the parameters needed by the the tosyncendpoint server.  After setting any
     * optional parameters, call the {@link InsertToSync#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertToSync#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.trip.expensemanager.tosyncendpoint.model.ToSync}
     * @since 1.13
     */
    protected InsertToSync(com.trip.expensemanager.tosyncendpoint.model.ToSync content) {
      super(Tosyncendpoint.this, "POST", REST_PATH, content, com.trip.expensemanager.tosyncendpoint.model.ToSync.class);
    }

    @Override
    public InsertToSync setAlt(java.lang.String alt) {
      return (InsertToSync) super.setAlt(alt);
    }

    @Override
    public InsertToSync setFields(java.lang.String fields) {
      return (InsertToSync) super.setFields(fields);
    }

    @Override
    public InsertToSync setKey(java.lang.String key) {
      return (InsertToSync) super.setKey(key);
    }

    @Override
    public InsertToSync setOauthToken(java.lang.String oauthToken) {
      return (InsertToSync) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertToSync setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertToSync) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertToSync setQuotaUser(java.lang.String quotaUser) {
      return (InsertToSync) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertToSync setUserIp(java.lang.String userIp) {
      return (InsertToSync) super.setUserIp(userIp);
    }

    @Override
    public InsertToSync set(String parameterName, Object value) {
      return (InsertToSync) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listToSync".
   *
   * This request holds the parameters needed by the tosyncendpoint server.  After setting any
   * optional parameters, call the {@link ListToSync#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListToSync listToSync() throws java.io.IOException {
    ListToSync result = new ListToSync();
    initialize(result);
    return result;
  }

  public class ListToSync extends TosyncendpointRequest<com.trip.expensemanager.tosyncendpoint.model.CollectionResponseToSync> {

    private static final String REST_PATH = "tosync";

    /**
     * Create a request for the method "listToSync".
     *
     * This request holds the parameters needed by the the tosyncendpoint server.  After setting any
     * optional parameters, call the {@link ListToSync#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListToSync#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListToSync() {
      super(Tosyncendpoint.this, "GET", REST_PATH, null, com.trip.expensemanager.tosyncendpoint.model.CollectionResponseToSync.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListToSync setAlt(java.lang.String alt) {
      return (ListToSync) super.setAlt(alt);
    }

    @Override
    public ListToSync setFields(java.lang.String fields) {
      return (ListToSync) super.setFields(fields);
    }

    @Override
    public ListToSync setKey(java.lang.String key) {
      return (ListToSync) super.setKey(key);
    }

    @Override
    public ListToSync setOauthToken(java.lang.String oauthToken) {
      return (ListToSync) super.setOauthToken(oauthToken);
    }

    @Override
    public ListToSync setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListToSync) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListToSync setQuotaUser(java.lang.String quotaUser) {
      return (ListToSync) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListToSync setUserIp(java.lang.String userIp) {
      return (ListToSync) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListToSync setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String syncType;

    /**

     */
    public java.lang.String getSyncType() {
      return syncType;
    }

    public ListToSync setSyncType(java.lang.String syncType) {
      this.syncType = syncType;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListToSync setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long userId;

    /**

     */
    public java.lang.Long getUserId() {
      return userId;
    }

    public ListToSync setUserId(java.lang.Long userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public ListToSync set(String parameterName, Object value) {
      return (ListToSync) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeToSync".
   *
   * This request holds the parameters needed by the tosyncendpoint server.  After setting any
   * optional parameters, call the {@link RemoveToSync#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveToSync removeToSync(java.lang.Long id) throws java.io.IOException {
    RemoveToSync result = new RemoveToSync(id);
    initialize(result);
    return result;
  }

  public class RemoveToSync extends TosyncendpointRequest<Void> {

    private static final String REST_PATH = "tosync/{id}";

    /**
     * Create a request for the method "removeToSync".
     *
     * This request holds the parameters needed by the the tosyncendpoint server.  After setting any
     * optional parameters, call the {@link RemoveToSync#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveToSync#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveToSync(java.lang.Long id) {
      super(Tosyncendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveToSync setAlt(java.lang.String alt) {
      return (RemoveToSync) super.setAlt(alt);
    }

    @Override
    public RemoveToSync setFields(java.lang.String fields) {
      return (RemoveToSync) super.setFields(fields);
    }

    @Override
    public RemoveToSync setKey(java.lang.String key) {
      return (RemoveToSync) super.setKey(key);
    }

    @Override
    public RemoveToSync setOauthToken(java.lang.String oauthToken) {
      return (RemoveToSync) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveToSync setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveToSync) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveToSync setQuotaUser(java.lang.String quotaUser) {
      return (RemoveToSync) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveToSync setUserIp(java.lang.String userIp) {
      return (RemoveToSync) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveToSync setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveToSync set(String parameterName, Object value) {
      return (RemoveToSync) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateToSync".
   *
   * This request holds the parameters needed by the tosyncendpoint server.  After setting any
   * optional parameters, call the {@link UpdateToSync#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.trip.expensemanager.tosyncendpoint.model.ToSync}
   * @return the request
   */
  public UpdateToSync updateToSync(com.trip.expensemanager.tosyncendpoint.model.ToSync content) throws java.io.IOException {
    UpdateToSync result = new UpdateToSync(content);
    initialize(result);
    return result;
  }

  public class UpdateToSync extends TosyncendpointRequest<com.trip.expensemanager.tosyncendpoint.model.ToSync> {

    private static final String REST_PATH = "tosync";

    /**
     * Create a request for the method "updateToSync".
     *
     * This request holds the parameters needed by the the tosyncendpoint server.  After setting any
     * optional parameters, call the {@link UpdateToSync#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateToSync#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.trip.expensemanager.tosyncendpoint.model.ToSync}
     * @since 1.13
     */
    protected UpdateToSync(com.trip.expensemanager.tosyncendpoint.model.ToSync content) {
      super(Tosyncendpoint.this, "PUT", REST_PATH, content, com.trip.expensemanager.tosyncendpoint.model.ToSync.class);
    }

    @Override
    public UpdateToSync setAlt(java.lang.String alt) {
      return (UpdateToSync) super.setAlt(alt);
    }

    @Override
    public UpdateToSync setFields(java.lang.String fields) {
      return (UpdateToSync) super.setFields(fields);
    }

    @Override
    public UpdateToSync setKey(java.lang.String key) {
      return (UpdateToSync) super.setKey(key);
    }

    @Override
    public UpdateToSync setOauthToken(java.lang.String oauthToken) {
      return (UpdateToSync) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateToSync setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateToSync) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateToSync setQuotaUser(java.lang.String quotaUser) {
      return (UpdateToSync) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateToSync setUserIp(java.lang.String userIp) {
      return (UpdateToSync) super.setUserIp(userIp);
    }

    @Override
    public UpdateToSync set(String parameterName, Object value) {
      return (UpdateToSync) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Tosyncendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Tosyncendpoint}. */
    @Override
    public Tosyncendpoint build() {
      return new Tosyncendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TosyncendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTosyncendpointRequestInitializer(
        TosyncendpointRequestInitializer tosyncendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(tosyncendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
